### ISSUE TITLE
Help with error when launching...

### ISSUE THREAD

**Issue by doublee313** [ayan4m1/atlas-tile-server#1]
I have installed with "npm install" and it seems to go but this comes up when starting:

PS D:\Servers\Atlas\atlas-tile-server-master> npm start

> atlas-tile-server@0.1.0 start D:\Servers\Atlas\atlas-tile-server-master
> node lib/index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'D:\Servers\Atlas\atlas-tile-server-master\lib\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atlas-tile-server@0.1.0 start: `node lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atlas-tile-server@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\atlas\AppData\Roaming\npm-cache\_logs\2019-02-27T01_27_54_492Z-debug.log

Thanks! Awesome work.

**Comment by ayan4m1** [comment]
Bad documentation on my part, you need to run `npm run build` before `npm start`. I'll update the readme. Thanks for reporting, hope that solves your issue!

**Comment by ayan4m1** [comment]
If you have any new issues, please feel free to open one. I am closing this as I feel it has been addressed both from a support and documentation perspective.

**Comment by doublee313** [comment]
Yes, sorry i was trying to get my 5x8 working with your tool. I'm using the
Atlas one now but noticed you had a scaling one.

http://atlas.doubleegaming.com:8901/

Do you have a Discord i can friend? I can show you my setup and what its
doing. Thank you.
